[CmdletBinding()]
param([switch]$Force)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$copilotRoot = if ($env:COPILOT_HOME) { $env:COPILOT_HOME } else { Join-Path $env:USERPROFILE ".copilot" }
$extensionInstall = Join-Path $copilotRoot "extensions\think-together"
$backupRoot = Join-Path $env:LOCALAPPDATA ("CopilotSourceBackups\think-together-" + (Get-Date -Format "yyyyMMdd-HHmmss"))

function Backup-ExistingPath {
    param([Parameter(Mandatory = $true)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return }
    New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null
    $backupPath = Join-Path $backupRoot (Split-Path -Leaf $Path)
    Move-Item -LiteralPath $Path -Destination $backupPath -Force
    Write-Host "Backed up $Path to $backupPath"
}

if (Test-Path -LiteralPath $extensionInstall) {
    $wrapperPath = Join-Path $extensionInstall "extension.mjs"
    $isGenerated = (Test-Path -LiteralPath $wrapperPath) -and
        ((Get-Content -LiteralPath $wrapperPath -TotalCount 1) -eq "// Generated by think-together install.ps1.")
    if ($isGenerated) {
        Remove-Item -LiteralPath $extensionInstall -Recurse -Force
    }
    elseif ($Force) {
        Backup-ExistingPath -Path $extensionInstall
    }
    else {
        throw "Cannot replace $extensionInstall because it already exists. Re-run with -Force to back it up first."
    }
}

New-Item -ItemType Directory -Force -Path $extensionInstall | Out-Null
$targetExtension = (Join-Path $repoRoot "extension.mjs").Replace("\", "/")
@"
// Generated by think-together install.ps1.
// Copilot CLI loads this installed wrapper, while source edits happen in the repo.
import "file:///$targetExtension";
"@ | Set-Content -Path (Join-Path $extensionInstall "extension.mjs") -Encoding UTF8
Copy-Item -LiteralPath (Join-Path $repoRoot "plugin.json") -Destination (Join-Path $extensionInstall "plugin.json") -Force

Write-Host "Installed Think Together extension."
Write-Host "Extension wrapper: $extensionInstall"
if (Test-Path -LiteralPath $backupRoot) { Write-Host "Backups: $backupRoot" }
